baseURL = "https://eshop-psi-ten.now.sh/"
languageCode = "en-us"
title = "Kavy's"
theme = "eshop"

[params]
  category = "Categories"
  pricerange = "Price Filter"
  Title = "Kavy's Collections"

[permalinks]
  products = "/:filename/"
[menu]
  [[menu.main]]
    name = "Collections"
    pre = "home"
    url = "/products/"
    weight = 1
  [[menu.main]]
    name = "Welcome"
    pre = "Collections"
    url = "/upcoming/upcoming"
    weight = 2
  [[menu.main]]
    name = "About Us"
    pre = "Upcoming Sale"
    url = "/contacts/contacts"
    weight = 3
[taxonomies]
  category = "categories"
  tag = "tags"
  pricerange = "pricerange"