baseURL = "https://eshop-psi-ten.now.sh/"
#baseURL = "https://kyva.ca/"
languageCode = "en-us"
title = "Kavy's"
theme = "eshop"

[params]
  category = "Categories"
  pricerange = "Price Filter"
  Title = "Kavy's Collections"

[permalinks]
  products = "/:filename/"
[menu]
  [[menu.main]]
    name = "Collections"
    pre = "home"
    url = "/products/"
    weight = 2
  [[menu.main]]
    name = "Welcome"
    pre = "Collections"
    url = "/upcoming/upcoming"
    weight = 1
  [[menu.main]]
    name = "About Us"
    pre = "Upcoming Sale"
    url = "/contacts/contacts"
    weight = 4
  [[menu.main]]
    name = "Baby Shop"
    pre = "Baby Shop"
    url = "/babylist/babylist"
  [[menu.main]]
    name = "ecwid"
    pre = "ecwid"
    url = "/ecwid/ecwid"  
    weight = 3
[taxonomies]
  category = "categories"
  tag = "tags"
  pricerange = "pricerange"